default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  # username: momento
  # password: vasco123

development:
  <<: *default
  database: simple_store_development

test:
  <<: *default
  database: simple_store_admin_test

production:
  <<: *default
  database: simple_store_production
  username: simple_store_admin
  password: <%= ENV["SIMPLE_STORE_ADMIN_DATABASE_PASSWORD"] %>
